name: "telegraph"
version: "0.0.1"
description: "Telegraph API wrapper for Dart"
author: "Sungjin Han <meinside@gmail.com>"

environment:
  sdk: '>=2.0.0-dev.54 <3.0.0'

dependencies:
  html: "^0.13.3"
  http: "^0.11.3"
  intl: "^0.15.7"

publish_to: "none"
